apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: gateway-policy
spec:
  default:
    sslPolicy: SSL_POLICY
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external-http