apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hc-policy
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 30
    healthyThreshold: 2
    unhealthyThreshold: 5
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        # port: PORT
        # portName: PORT_NAME
        # host: HOST
        # requestPath: REQUEST_PATH
        # response: RESPONSE
        # proxyHeader: PROXY_HEADER
  targetRef:
    group: ""
    kind: Service
    name: dev-team-1-app-v1